### ISSUE TITLE
android studio and github - push and clone

### ISSUE THREAD

**Issue by diamantoula** [teiser2016/Game#1]
- [x] push project from android studio to github
- [x] clone project from github to android studio

**Comment by diamantoula** [comment]
polu kalo kai eukolo tutorial!
https://www.youtube.com/watch?v=3ztsB7Zx9xo

**Comment by diamantoula** [comment]
polu kalo kai eukolo tutorial!
https://www.youtube.com/watch?v=3ztsB7Zx9xo

**Comment by dimisg** [comment]
meta apo polles prospa8ies, kai poli pedema... kataferan na to kanw... aaaax nio8w ikanopiisi
