### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by nikosstath** [teiser2016/Game#11]
Στο commit του knife εννοούσα, libraries και όχι packages. Το πρόβλημα έχει να κάνει με τις βιβλιοθήκες του Android studio! Δυστυχώς θα δουλεύω μόνο απ' το internetcafe! Μέχρι την Τετάρτη θα ανεβάσω κι άλλο κώδικα!

**Comment by diamantoula** [comment]
mipws th eprepe na exeis kai metavlites gia tis suntetagmenes? lat kai lng?
