### ISSUE TITLE
Η δομή θέλει επειγόντως αλλαγή!

### ISSUE THREAD

**Issue by nikosstath** [teiser2016/Game#17]
Η δομή είναι κυριολεκτικά για το ανάθεμα. Πρέπει να γίνει αλλαγή, + ότι θέλω να κάνω κλάση save/load η οποία δεν πρόκεται να δουλέψει, αν δεν αλλάξει η δομή!

**Comment by kakos5002** [comment]
Έχουμε πόλλα Bugs ρε παιδεία ας κάνει κάποιος κάτι !!!!
