### ISSUE TITLE
δημιουργια μοντελων των πινακων της βασης για ευκολοτερη διαχειριση των δεδομενων 

### ISSUE THREAD

**Issue by diamantoula** [teiser2016/Game#19]
- [x] δημιουργια πακετου για τα μοντελα
- [x] δημιουργια μοντελου object
- [x] δημιουργια μοντελου npc
- [x] δημιουργια μοντελου user
- [x] δημιουργια μοντελου charoption

**Comment by stavroulab** [comment]
dimiourgia klasis User.java - Xrisi tis volley.lib
o xristis vlepei ta stoixeia pou exei pliktrologisei o idios dinontas to user_id tou
https://www.simplifiedcoding.net/retrieve-data-from-mysql-database-in-android-using-volley/  : edw vrika to tutorial pou xrisimopoiisa
stin klasi Config.java, sto url, i dieuthinsi einai apo ton upologisti mou.tin vriskeis sto cmd me tin entoli ipconfig
