### ISSUE TITLE
AsyncTask gia na travame kai na eisagoume dedomena stin vasi

### ISSUE THREAD

**Issue by diamantoula** [teiser2016/Game#22]

**Comment by diamantoula** [comment]
telika den tha xrisimopoiisoume AsyncTask, afou vrike o apostolis allo tropo, eukolo, me tin volley library

**Comment by stavroulab** [comment]
stin klasi User.java xrisimopoiithike episis volley library opou travaei stoixeia apo tin vasi

**Comment by diamantoula** [comment]
genika, gia na einai ligo omoiomorfos o kwdikas n xrisimopoiisoume oloi to volley
