### ISSUE TITLE
story

### ISSUE THREAD

**Issue by diamantoula** [teiser2016/Game#3]
- [x] epilogi thematos
- [x] istoria tou paixnidiou
- [x] domh xaraktirwn xristi (biografia, idiotites)
- [x] domh npc's (statikoi xaraktires)
- [x] domh objects (statika antikeimena)

θεμα: απαγωγη
χαρακτηρες: 1 ντεντεκτιβ (για αρχη)
αντικειμενα: 5?
NPCs (non-player character): 5?

μολισ ο χρηστησ ανοιγει την εφαρμογη εμφανιζεται μνμ το οποιο διηγειται περιληπτικα την ιστορια και δινει στο χρηστη την τοποθεσια στην οποια πρεπει να παει ωστε να μπορεσει να ξεκινησει κανονικα το παιχνιδι.
απο εκει και περα, και σε καθε νεα τοποθεσια, θα του δινονται στοιχεια τα οποια θα τον βοηθουν να βρει την επομενη τοποθεσιεσ εωσ οτου τερματισει το παιχνιδι.
σε αυτεσ τισ τοποθεσιεσ (προκαθορισμενεσ) θα υπαρχουν ειτε αντικειμενα ειτε NPCs.

τα αντικειμενα θα μπορει να τα χρησιμοποιησει επιτοπου ή να τα αποθηκευσει στο inventory του. καποια απο αυτα θα μπορουν να επηρεασουν ορισμενεσ ιδιοτητεσ του χαρακτηρα του χρηστη (πχ. ιδιοτητα: intelligence - σε εναν παιχτησ με μεγαλυτερο intelligence θα δινονται καλυτερα στοιχεια).

οι NPCs δινουν επιτοπου στοιχεια (ή γριφοι)

ο παιχτησ πρεπει να παει στισ τοποθεσιεσ των αντικειμενων και NPCs με συγκεκριμενη σειρα. 

το παιχνιδι τερματιζει οταν ο παιχτησ φτασει στον τελευταιο NPC (θυμα)

προτασεισ???

**Comment by nikosstath** [comment]
Καλό θα ήταν να κάνουμε έναν μετρητή, που θα αυξάνεται ή μειώνεται όταν τελειώνει το quest ο χρήστης με το NPC. Όταν φτάσει στο τελευταίο npc και πάει σε συγκεκριμένο αριθμό ο μετρητής θα ολοκληρώνεται το παιχνίδι. Όλα τα NPCs θα είναι ενεργά;

**Comment by dimisg** [comment]
kai kalo 8a itan na bgaloume ena basiko story.... mpas kai broume kai ti 8a baloume sthn basi.....

**Comment by nikosstath** [comment]
@dimisg  για inventory εννοείς; τι items θα βάλουμε και τa NPCs;

**Comment by diamantoula** [comment]
an telika xrisimopoihsoume kai to intelligence stous characters dn tha itan kalutera ta antikeimena i ta npc's st opoia allazei o vathmos tou intelligence na einai entalws tuxaia? giati an vriskontai anamesa se auta ta opoia th exoume arithmimena (afou theloume o xristis na akolouthisei sugkekrimeni seira) tote oloi oi xristes tha auksanoun to intelligence kai dn th exei noima...
