### ISSUE TITLE
σχετικα με τη βαση...

### ISSUE THREAD

**Issue by diamantoula** [teiser2016/Game#4]
https://www.youtube.com/watch?v=4-xXnj3Jxz8

mongolab https://mlab.com/welcome/

αυτο εννουσα.
με αυτον τον τροπο δε χρειαζεται να ενσωματτωσουμε τη βαση ή να την συνδεσουμε με την εφαρμογη με πολυπλοκο τροπο. αν την δημιουργησουμε τοτε μπορουμε να εχουμε απομακρυσμενη προσβαση μονο με link.

ριξτε το μια ματια μηπωσ βολευει περισσοτερο??
στην ιστοσελιδα εχει και πολυ αναλυτικα tutorial http://docs.mlab.com/

**Comment by dimisg** [comment]
eeeem nai... auto aposo ida omos einai gia web-efarmogi meso browser... de 3erw kata poso ginete gia android
