### ISSUE TITLE
δημιουργια βασης

### ISSUE THREAD

**Issue by diamantoula** [teiser2016/Game#5]

**Comment by diamantoula** [comment]
gia tis suntetagmenes th itan kalo na dimiourgisete 2 pedia ena gia to latitude kai ena gia to longitude, giati mesa stis sunartiseis tis zitoun ksexwrista kai an tis exete se mazi se ena pediotha einai pio duskolo na tis diaxeiristoume

**Comment by Mitsakos46** [comment]
- [ ] create databases
- [ ] create tables
- [ ] insert datas

**Comment by Mitsakos46** [comment]
- [x] create databases
- [x] create tables
- [x] insert datas
