### ISSUE TITLE
Items;;;

### ISSUE THREAD

**Issue by nikosstath** [teiser2016/Game#7]
Στο χρονοδιάγραμμα στην 1η εβδομάδα, λέμε αντικείμενα πάνω στον χάρτη. Αντικείμενα ο character δεν θα έχει;; Επίσης στην 3η εβδομάδα λέμε αλληλεπίδραση με τον χρήστη. Δεν πρέπει πρώτα να τα φτιάξουμε;

**Comment by diamantoula** [comment]
mipws th eprepe na exeis kai metavlites gia tis suntetagmenes? lat kai lng?
